@extends('layouts.template')

@section('body')
<h1 class="page-header mb-4">
  Privacy Policy
</h1>

<div>
  <p><strong><u>Kweh! Bot</u></strong></p>
  <p>The following data are collected by Kweh!</p>
  <ul>
    <li>Discord server information including but not limited to names, ids and server specific settings</li>
    <li>Registered Discord users' lodestone characters</li>
    <li>Discord server ids and channel ids if lodestone news or fashion report subscriptions has been enabled</li>
    <li>Channel ids and names if default channel is setup</li>
    <li>Commands issued</li>
    <li>Generated character profile images</li>
  </ul>

  <p>Kweh! logs only valid commands it recognizes (e.g. !register, !profile).</p>

  <p><strong><u>Login with Discord</u></strong></p>

  <p>The following data are collected when you login with Discord on this website to manage your server specific settings.</p>

  <ul>
    <li>Discord servers that you're in</li>
    <li>Your basic Discord account information including but not limited to username, id and avatar url</li>
  </ul>

  <p><strong><u>Access Logs</u></strong></p>
  <p>This website collects personal data through its server access logs. When you access this website, your internet address is automatically collected and placed in our access logs. We record the URLs of the pages you visit, the times and dates of such visits.</p>

  <p>This information may include Internet protocol (IP) addresses, browser type and version, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and/or clickstream data, number of visits, websites from which you accessed our site (Referrer), and websites that are accessed by your system via our website.</p>

  <p>The processing of this data is necessary for the provision and the security of this website.</p>

  <p><strong><u>Google Analytics</u></strong></p>
  <p>This website uses Google Analytics. Google Analytics employs cookies that are stored on your computer to facilitate an analysis of your use of the website. The information generated by these cookies, such as time, place and frequency of your visits to our site, including your IP address, is transmitted to Google.</p>

  <p>Google Analytics offers a deactivation add-on for most current browsers that provides you with more control over what data Google can collect on websites you access. You can find additional information about the add-on <a href="https://tools.google.com/dlpage/gaoptout/" target="_blank">here</a>.</p>
</div>
@endsection
